### ISSUE TITLE
Unable to run Trimmomatic with PE commands

### ISSUE THREAD

**Issue by OliviaRN** [OliviaRN/Tepoztlan_ITS#4]
Hola Alicia,

Intenté usar los comandos para secuencias Pair End, sin embargo no lo logré, por lo tanto usé los comandos de SE (Creo que no estuvo bien hacer eso). Lo revisamos más tarde. Adjunto lo que hice.

Gracias

# Unable to run Trimmomatic with PE commands

According to the Trimmomatic manual, in the section *Input/Output Files* , page 4:

Paired-end mode requires 2 input files (for forward and reverse reads) and 4 output files (for
forward paired, forward unpaired, reverse paired and reverse unpaired reads).

And the page 11, the *Pair End example* 

´´´
java -jar trimmomatic-0.30.jar PE s_1_1_sequence.txt.gz s_1_2_sequence.txt.gz
lane1_forward_paired.fq.gz lane1_forward_unpaired.fq.gz lane1_reverse_paired.fq.gz
lane1_reverse_unpaired.fq.gz ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3
TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
´´´

This is what I typed:

´´´
 ~/Tepoztlan_ITS/bin$ java -jar trimmomatic-0.39.jar PE ../data/tepoz/SCC1J_S3_L001_R1_001.fastq.gz ../data/tepoz/SCC1J_S3_L001_R2_001.fastq.gz ../data/trimfilter/SCC1J_S3_L001_R1_001_lane1F_Paired ../data/trimfilter/SCC1J_S3_L001_R1_001_lane1F_Unpaired trimmed.fastq.gz ../data/trimfilter/SCC1J_S3_L001_R2_001_lane1R_Pairtrimmed.fastq.gz ../data/trimfilter/SCC1J_S3_L001_R2_001_lane1R_Unptrimmed.fastq.gz ILLUMINACLIP:TruSeq3-SE.fa:2:30:10 SLIDINGWINDOW:7:20
TrimmomaticPE: Started with arguments: ../data/tepoz/SCC1J_S3_L001_R1_001.fastq.gz ../data/tepoz/SCC1J_S3_L001_R2_001.fastq.gz ../data/trimfilter/SCC1J_S3_L001_R1_001_lane1F_Paired ../data/trimfilter/SCC1J_S3_L001_R1_001_lane1F_Unpaired trimmed.fastq.gz ../data/trimfilter/SCC1J_S3_L001_R2_001_lane1R_Pairtrimmed.fastq.gz ../data/trimfilter/SCC1J_S3_L001_R2_001_lane1R_Unptrimmed.fastq.gz ILLUMINACLIP:TruSeq3-SE.fa:2:30:10 SLIDINGWINDOW:7:20
´´´

The Trimming was not done and I got the next Error message:

Exception in thread "main" java.lang.RuntimeException: Unknown trimmer: ../data/trimfilter/SCC1J_S3_L001_R2_001_lane1R_Unptrimmed.fastq.gz
	at org.usadellab.trimmomatic.trim.TrimmerFactory.makeTrimmer(TrimmerFactory.java:73)
	at org.usadellab.trimmomatic.Trimmomatic.createTrimmers(Trimmomatic.java:59)
	at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:552)
	at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)

**Comment by OliviaRN** [comment]
Es correcto usar los comandos para secuencias "Single End".
